### ISSUE TITLE
Will this fail in the browser if Firebase is included as an NPM dependency? Yes.

### ISSUE THREAD

**Issue by aequitable** [jacobobryant/trident#9]
Yes. Yes, it does. 😄 In fact, the failure is quite spectacular: `ReferenceError: require is not defined`

https://github.com/jacobobryant/trident/blob/968a096481363d8312d32e018ccf2a1a839b3365/src/trident/firestore/util.cljs#L15

I tripped over this while converting from including Firebase via `<script>` tags to `shadow-cljs` and `NPM`.

I'm new to CLJS, so not sure of the right way to fix...if I come up with something (better that putting the `<script>` tags back) I'll submit a PR.

**Comment by aequitable** [comment]
Of course, putting back the `<script>` tags, while leaving `firebase/app` from NPM in the build, results in...
```
@firebase/app: 
    Warning: Firebase is already defined in the global scope. Please make sure
    Firebase library is only loaded once.
```

**Comment by jacobobryant** [comment]
Heh, sorry about that. The lowest effort fix would be to add another clause to that or expression, right below the line you quoted (on my phone now and github/firefox won't let me copy from there...). The clause needs to return the Timestamp object correctly if you're using the client sdk through npm and return something false otherwise. I'm not sure exactly the correct way to do that since I always used script tags myself, but shouldn't be that complex. I can take a look at it in two days, or happy to accept a PR if you get to it before then.

**Comment by jacobobryant** [comment]
This has turned out to be somewhat complex since:

1. as far as I'm aware, npm modules can't be dynamically imported in a browser context
2. there's also a bunch of interop code in `trident.firestore` and `trident.firestore.util` that currently uses cljs-oops and would break if the firebase module went through the closure compiler

I think the best solution is to provide an additional namespace `trident.firestore.npm` that will statically import `Timestamp` and will use regular interop calls (which will get minified appropriately by the closure compiler).

Normally in this kind of situation it'd probably be better to only support installing dependency modules through npm instead of adding them with script tags. But in this case script tags are nice since they let you use Firebase's special hosting urls which handle project config for you.

I've made the `trident.firestore.npm` namespace already actually, just haven't tested it. It's a quick hack; everything's copy pasted with the needed changes. It'll get the job done for now though. Planning to merge it tomorrow after testing.

**Comment by jacobobryant** [comment]
TIL that shadow-cljs doesn't put npm deps through advanced compilation, so actually this isn't as complicated as I thought. I've fixed this issue with https://github.com/jacobobryant/trident/commit/2513f045cbdb475b57c2f8fd9c0e647de491195d.

@aequitable upgrade to `trident/firestore {:mvn/version "0.2.3"}` and feel free to re-open this issue if it's still broken.

**Comment by jacobobryant** [comment]
Doh, I forgot to actually publish the new version. It's on clojars now.

**Comment by aequitable** [comment]
Thank you @jacobobryant! Took me awhile to get back to this project, but I can confirm this fix works for me!

**Comment by jacobobryant** [comment]
Great! Let me know if you run into any other issues.
